#! /bin/sh

sxhkd &
polybar black -c ~/.config/polybar/config &
picom & 
feh --bg-fill ~/.wallpapers/minimal.png &
start-pulseaudio-x11 &
xrdb merge ~/.Xresources & 
mopidy &

bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          7
bsp config presel_feedback_color "#ffffff" 
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 20

bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"

